### PR TITLE
Removed '#ifdef COCOAPODS' part to correct work with cocoapods 1.0.0

### PR DESCRIPTION
**Pull request by frizzle**

### CODE REVIEW

**Comment by JanX2** [comment]
I usually don’t use cocoapods. Do you know why this has become unnecessary?

**Comment by frizzle** [comment]
As I get it they have removed 'Pods-environment.h' in cocoapods version 1.0.0. So import of this file bring compilation error. And it work scorrectly without importing Pods-environment.h
